// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xfilt.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XFilt_CfgInitialize(XFilt *InstancePtr, XFilt_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Control_bus_BaseAddress = ConfigPtr->Control_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XFilt_Start(XFilt *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFilt_ReadReg(InstancePtr->Control_bus_BaseAddress, XFILT_CONTROL_BUS_ADDR_AP_CTRL) & 0x80;
    XFilt_WriteReg(InstancePtr->Control_bus_BaseAddress, XFILT_CONTROL_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XFilt_IsDone(XFilt *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFilt_ReadReg(InstancePtr->Control_bus_BaseAddress, XFILT_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XFilt_IsIdle(XFilt *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFilt_ReadReg(InstancePtr->Control_bus_BaseAddress, XFILT_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XFilt_IsReady(XFilt *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFilt_ReadReg(InstancePtr->Control_bus_BaseAddress, XFILT_CONTROL_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XFilt_EnableAutoRestart(XFilt *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFilt_WriteReg(InstancePtr->Control_bus_BaseAddress, XFILT_CONTROL_BUS_ADDR_AP_CTRL, 0x80);
}

void XFilt_DisableAutoRestart(XFilt *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFilt_WriteReg(InstancePtr->Control_bus_BaseAddress, XFILT_CONTROL_BUS_ADDR_AP_CTRL, 0);
}

void XFilt_InterruptGlobalEnable(XFilt *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFilt_WriteReg(InstancePtr->Control_bus_BaseAddress, XFILT_CONTROL_BUS_ADDR_GIE, 1);
}

void XFilt_InterruptGlobalDisable(XFilt *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFilt_WriteReg(InstancePtr->Control_bus_BaseAddress, XFILT_CONTROL_BUS_ADDR_GIE, 0);
}

void XFilt_InterruptEnable(XFilt *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XFilt_ReadReg(InstancePtr->Control_bus_BaseAddress, XFILT_CONTROL_BUS_ADDR_IER);
    XFilt_WriteReg(InstancePtr->Control_bus_BaseAddress, XFILT_CONTROL_BUS_ADDR_IER, Register | Mask);
}

void XFilt_InterruptDisable(XFilt *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XFilt_ReadReg(InstancePtr->Control_bus_BaseAddress, XFILT_CONTROL_BUS_ADDR_IER);
    XFilt_WriteReg(InstancePtr->Control_bus_BaseAddress, XFILT_CONTROL_BUS_ADDR_IER, Register & (~Mask));
}

void XFilt_InterruptClear(XFilt *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFilt_WriteReg(InstancePtr->Control_bus_BaseAddress, XFILT_CONTROL_BUS_ADDR_ISR, Mask);
}

u32 XFilt_InterruptGetEnabled(XFilt *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XFilt_ReadReg(InstancePtr->Control_bus_BaseAddress, XFILT_CONTROL_BUS_ADDR_IER);
}

u32 XFilt_InterruptGetStatus(XFilt *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XFilt_ReadReg(InstancePtr->Control_bus_BaseAddress, XFILT_CONTROL_BUS_ADDR_ISR);
}

