-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2016.2
-- Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity filt_Loop_1_proc is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    wrk_dst_mat_data_stream_0_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    wrk_dst_mat_data_stream_0_V_full_n : IN STD_LOGIC;
    wrk_dst_mat_data_stream_0_V_write : OUT STD_LOGIC;
    wrk_dst_mat_data_stream_1_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    wrk_dst_mat_data_stream_1_V_full_n : IN STD_LOGIC;
    wrk_dst_mat_data_stream_1_V_write : OUT STD_LOGIC;
    wrk_dst_mat_data_stream_2_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    wrk_dst_mat_data_stream_2_V_full_n : IN STD_LOGIC;
    wrk_dst_mat_data_stream_2_V_write : OUT STD_LOGIC;
    wrk_mats_0_data_stream_0_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    wrk_mats_0_data_stream_0_V_empty_n : IN STD_LOGIC;
    wrk_mats_0_data_stream_0_V_read : OUT STD_LOGIC;
    wrk_mats_0_data_stream_1_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    wrk_mats_0_data_stream_1_V_empty_n : IN STD_LOGIC;
    wrk_mats_0_data_stream_1_V_read : OUT STD_LOGIC;
    wrk_mats_0_data_stream_2_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    wrk_mats_0_data_stream_2_V_empty_n : IN STD_LOGIC;
    wrk_mats_0_data_stream_2_V_read : OUT STD_LOGIC;
    wrk_mats_2_data_stream_0_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    wrk_mats_2_data_stream_0_V_empty_n : IN STD_LOGIC;
    wrk_mats_2_data_stream_0_V_read : OUT STD_LOGIC;
    wrk_mats_2_data_stream_1_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    wrk_mats_2_data_stream_1_V_empty_n : IN STD_LOGIC;
    wrk_mats_2_data_stream_1_V_read : OUT STD_LOGIC;
    wrk_mats_2_data_stream_2_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    wrk_mats_2_data_stream_2_V_empty_n : IN STD_LOGIC;
    wrk_mats_2_data_stream_2_V_read : OUT STD_LOGIC;
    sel_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    sel_empty_n : IN STD_LOGIC;
    sel_read : OUT STD_LOGIC );
end;


architecture behav of filt_Loop_1_proc is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_st1_fsm_0 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_st2_fsm_1 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_pp0_stg0_fsm_2 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_st5_fsm_3 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv8_F0 : STD_LOGIC_VECTOR (7 downto 0) := "11110000";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv9_140 : STD_LOGIC_VECTOR (8 downto 0) := "101000000";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_sig_cseq_ST_st1_fsm_0 : STD_LOGIC;
    signal ap_sig_22 : BOOLEAN;
    signal wrk_dst_mat_data_stream_0_V_blk_n : STD_LOGIC;
    signal ap_sig_cseq_ST_pp0_stg0_fsm_2 : STD_LOGIC;
    signal ap_sig_75 : BOOLEAN;
    signal ap_reg_ppiten_pp0_it1 : STD_LOGIC := '0';
    signal ap_reg_ppiten_pp0_it0 : STD_LOGIC := '0';
    signal tmp_101_i_reg_197 : STD_LOGIC_VECTOR (0 downto 0);
    signal wrk_dst_mat_data_stream_1_V_blk_n : STD_LOGIC;
    signal wrk_dst_mat_data_stream_2_V_blk_n : STD_LOGIC;
    signal wrk_mats_0_data_stream_0_V_blk_n : STD_LOGIC;
    signal wrk_mats_0_data_stream_1_V_blk_n : STD_LOGIC;
    signal wrk_mats_0_data_stream_2_V_blk_n : STD_LOGIC;
    signal wrk_mats_2_data_stream_0_V_blk_n : STD_LOGIC;
    signal wrk_mats_2_data_stream_1_V_blk_n : STD_LOGIC;
    signal wrk_mats_2_data_stream_2_V_blk_n : STD_LOGIC;
    signal sel_blk_n : STD_LOGIC;
    signal col_i_reg_156 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_101_i_fu_167_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_109 : BOOLEAN;
    signal exitcond1_i_fu_173_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_cseq_ST_st2_fsm_1 : STD_LOGIC;
    signal ap_sig_119 : BOOLEAN;
    signal row_fu_179_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal row_reg_205 : STD_LOGIC_VECTOR (7 downto 0);
    signal exitcond_i_fu_185_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_151 : BOOLEAN;
    signal col_fu_191_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal row_i_reg_145 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_sig_cseq_ST_st5_fsm_3 : STD_LOGIC;
    signal ap_sig_174 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_183 : BOOLEAN;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_st1_fsm_0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_continue)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and not((ap_const_lv1_0 = exitcond1_i_fu_173_p2)))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_reg_ppiten_pp0_it0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_2) and not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and ap_sig_151)) and not((ap_const_lv1_0 = exitcond_i_fu_185_p2)))) then 
                    ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and (ap_const_lv1_0 = exitcond1_i_fu_173_p2))) then 
                    ap_reg_ppiten_pp0_it0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_reg_ppiten_pp0_it1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_2) and not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and ap_sig_151)) and (ap_const_lv1_0 = exitcond_i_fu_185_p2))) then 
                    ap_reg_ppiten_pp0_it1 <= ap_const_logic_1;
                elsif ((((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and (ap_const_lv1_0 = exitcond1_i_fu_173_p2)) or ((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_2) and not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and ap_sig_151)) and not((ap_const_lv1_0 = exitcond_i_fu_185_p2))))) then 
                    ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    col_i_reg_156_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_2) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and ap_sig_151)) and (ap_const_lv1_0 = exitcond_i_fu_185_p2))) then 
                col_i_reg_156 <= col_fu_191_p2;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and (ap_const_lv1_0 = exitcond1_i_fu_173_p2))) then 
                col_i_reg_156 <= ap_const_lv9_0;
            end if; 
        end if;
    end process;

    row_i_reg_145_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st5_fsm_3)) then 
                row_i_reg_145 <= row_reg_205;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not(ap_sig_109))) then 
                row_i_reg_145 <= ap_const_lv8_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1)) then
                row_reg_205 <= row_fu_179_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not(ap_sig_109))) then
                tmp_101_i_reg_197 <= tmp_101_i_fu_167_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_reg_ppiten_pp0_it1, ap_reg_ppiten_pp0_it0, ap_sig_109, exitcond1_i_fu_173_p2, exitcond_i_fu_185_p2, ap_sig_151)
    begin
        case ap_CS_fsm is
            when ap_ST_st1_fsm_0 => 
                if (not(ap_sig_109)) then
                    ap_NS_fsm <= ap_ST_st2_fsm_1;
                else
                    ap_NS_fsm <= ap_ST_st1_fsm_0;
                end if;
            when ap_ST_st2_fsm_1 => 
                if (not((ap_const_lv1_0 = exitcond1_i_fu_173_p2))) then
                    ap_NS_fsm <= ap_ST_st1_fsm_0;
                else
                    ap_NS_fsm <= ap_ST_pp0_stg0_fsm_2;
                end if;
            when ap_ST_pp0_stg0_fsm_2 => 
                if (not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and ap_sig_151)) and not((ap_const_lv1_0 = exitcond_i_fu_185_p2))))) then
                    ap_NS_fsm <= ap_ST_pp0_stg0_fsm_2;
                elsif (((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and ap_sig_151)) and not((ap_const_lv1_0 = exitcond_i_fu_185_p2)))) then
                    ap_NS_fsm <= ap_ST_st5_fsm_3;
                else
                    ap_NS_fsm <= ap_ST_pp0_stg0_fsm_2;
                end if;
            when ap_ST_st5_fsm_3 => 
                ap_NS_fsm <= ap_ST_st2_fsm_1;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;

    ap_done_assign_proc : process(ap_done_reg, exitcond1_i_fu_173_p2, ap_sig_cseq_ST_st2_fsm_1)
    begin
        if (((ap_const_logic_1 = ap_done_reg) or ((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and not((ap_const_lv1_0 = exitcond1_i_fu_173_p2))))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_sig_cseq_ST_st1_fsm_0)
    begin
        if (((ap_const_logic_0 = ap_start) and (ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(exitcond1_i_fu_173_p2, ap_sig_cseq_ST_st2_fsm_1)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and not((ap_const_lv1_0 = exitcond1_i_fu_173_p2)))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_109_assign_proc : process(ap_start, ap_done_reg, sel_empty_n)
    begin
                ap_sig_109 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (sel_empty_n = ap_const_logic_0));
    end process;


    ap_sig_119_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_119 <= (ap_const_lv1_1 = ap_CS_fsm(1 downto 1));
    end process;


    ap_sig_151_assign_proc : process(wrk_dst_mat_data_stream_0_V_full_n, wrk_dst_mat_data_stream_1_V_full_n, wrk_dst_mat_data_stream_2_V_full_n, wrk_mats_0_data_stream_0_V_empty_n, wrk_mats_0_data_stream_1_V_empty_n, wrk_mats_0_data_stream_2_V_empty_n, wrk_mats_2_data_stream_0_V_empty_n, wrk_mats_2_data_stream_1_V_empty_n, wrk_mats_2_data_stream_2_V_empty_n, tmp_101_i_reg_197)
    begin
                ap_sig_151 <= ((wrk_mats_0_data_stream_0_V_empty_n = ap_const_logic_0) or (wrk_mats_0_data_stream_1_V_empty_n = ap_const_logic_0) or (wrk_mats_0_data_stream_2_V_empty_n = ap_const_logic_0) or (wrk_mats_2_data_stream_0_V_empty_n = ap_const_logic_0) or (wrk_mats_2_data_stream_1_V_empty_n = ap_const_logic_0) or (wrk_mats_2_data_stream_2_V_empty_n = ap_const_logic_0) or ((tmp_101_i_reg_197 = ap_const_lv1_0) and (wrk_dst_mat_data_stream_0_V_full_n = ap_const_logic_0)) or ((tmp_101_i_reg_197 = ap_const_lv1_0) and (wrk_dst_mat_data_stream_1_V_full_n = ap_const_logic_0)) or ((tmp_101_i_reg_197 = ap_const_lv1_0) and (wrk_dst_mat_data_stream_2_V_full_n = ap_const_logic_0)) or (not((tmp_101_i_reg_197 = ap_const_lv1_0)) and (wrk_dst_mat_data_stream_0_V_full_n = ap_const_logic_0)) or (not((tmp_101_i_reg_197 = ap_const_lv1_0)) and (wrk_dst_mat_data_stream_1_V_full_n = ap_const_logic_0)) or (not((tmp_101_i_reg_197 = ap_const_lv1_0)) and (wrk_dst_mat_data_stream_2_V_full_n = ap_const_logic_0)));
    end process;


    ap_sig_174_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_174 <= (ap_const_lv1_1 = ap_CS_fsm(3 downto 3));
    end process;


    ap_sig_183_assign_proc : process(ap_sig_cseq_ST_pp0_stg0_fsm_2, ap_reg_ppiten_pp0_it1, ap_sig_151)
    begin
                ap_sig_183 <= ((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_2) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and ap_sig_151)));
    end process;


    ap_sig_22_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_22 <= (ap_CS_fsm(0 downto 0) = ap_const_lv1_1);
    end process;


    ap_sig_75_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_75 <= (ap_const_lv1_1 = ap_CS_fsm(2 downto 2));
    end process;


    ap_sig_cseq_ST_pp0_stg0_fsm_2_assign_proc : process(ap_sig_75)
    begin
        if (ap_sig_75) then 
            ap_sig_cseq_ST_pp0_stg0_fsm_2 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_pp0_stg0_fsm_2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st1_fsm_0_assign_proc : process(ap_sig_22)
    begin
        if (ap_sig_22) then 
            ap_sig_cseq_ST_st1_fsm_0 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st1_fsm_0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st2_fsm_1_assign_proc : process(ap_sig_119)
    begin
        if (ap_sig_119) then 
            ap_sig_cseq_ST_st2_fsm_1 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st2_fsm_1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st5_fsm_3_assign_proc : process(ap_sig_174)
    begin
        if (ap_sig_174) then 
            ap_sig_cseq_ST_st5_fsm_3 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st5_fsm_3 <= ap_const_logic_0;
        end if; 
    end process;

    col_fu_191_p2 <= std_logic_vector(unsigned(col_i_reg_156) + unsigned(ap_const_lv9_1));
    exitcond1_i_fu_173_p2 <= "1" when (row_i_reg_145 = ap_const_lv8_F0) else "0";
    exitcond_i_fu_185_p2 <= "1" when (col_i_reg_156 = ap_const_lv9_140) else "0";
    row_fu_179_p2 <= std_logic_vector(unsigned(row_i_reg_145) + unsigned(ap_const_lv8_1));

    sel_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_sig_cseq_ST_st1_fsm_0, sel_empty_n)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))))) then 
            sel_blk_n <= sel_empty_n;
        else 
            sel_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    sel_read_assign_proc : process(ap_sig_cseq_ST_st1_fsm_0, ap_sig_109)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not(ap_sig_109))) then 
            sel_read <= ap_const_logic_1;
        else 
            sel_read <= ap_const_logic_0;
        end if; 
    end process;

    tmp_101_i_fu_167_p2 <= "1" when (sel_dout = ap_const_lv32_1) else "0";

    wrk_dst_mat_data_stream_0_V_blk_n_assign_proc : process(wrk_dst_mat_data_stream_0_V_full_n, ap_sig_cseq_ST_pp0_stg0_fsm_2, ap_reg_ppiten_pp0_it1, tmp_101_i_reg_197)
    begin
        if ((((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_2) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and not((tmp_101_i_reg_197 = ap_const_lv1_0))) or ((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_2) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and (tmp_101_i_reg_197 = ap_const_lv1_0)))) then 
            wrk_dst_mat_data_stream_0_V_blk_n <= wrk_dst_mat_data_stream_0_V_full_n;
        else 
            wrk_dst_mat_data_stream_0_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    wrk_dst_mat_data_stream_0_V_din_assign_proc : process(wrk_mats_0_data_stream_0_V_dout, wrk_mats_2_data_stream_0_V_dout, tmp_101_i_reg_197, ap_sig_183)
    begin
        if (ap_sig_183) then
            if (not((tmp_101_i_reg_197 = ap_const_lv1_0))) then 
                wrk_dst_mat_data_stream_0_V_din <= wrk_mats_2_data_stream_0_V_dout;
            elsif ((tmp_101_i_reg_197 = ap_const_lv1_0)) then 
                wrk_dst_mat_data_stream_0_V_din <= wrk_mats_0_data_stream_0_V_dout;
            else 
                wrk_dst_mat_data_stream_0_V_din <= "XXXXXXXX";
            end if;
        else 
            wrk_dst_mat_data_stream_0_V_din <= "XXXXXXXX";
        end if; 
    end process;


    wrk_dst_mat_data_stream_0_V_write_assign_proc : process(ap_sig_cseq_ST_pp0_stg0_fsm_2, ap_reg_ppiten_pp0_it1, tmp_101_i_reg_197, ap_sig_151)
    begin
        if ((((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_2) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and (tmp_101_i_reg_197 = ap_const_lv1_0) and not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and ap_sig_151))) or ((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_2) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and not((tmp_101_i_reg_197 = ap_const_lv1_0)) and not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and ap_sig_151))))) then 
            wrk_dst_mat_data_stream_0_V_write <= ap_const_logic_1;
        else 
            wrk_dst_mat_data_stream_0_V_write <= ap_const_logic_0;
        end if; 
    end process;


    wrk_dst_mat_data_stream_1_V_blk_n_assign_proc : process(wrk_dst_mat_data_stream_1_V_full_n, ap_sig_cseq_ST_pp0_stg0_fsm_2, ap_reg_ppiten_pp0_it1, tmp_101_i_reg_197)
    begin
        if ((((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_2) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and not((tmp_101_i_reg_197 = ap_const_lv1_0))) or ((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_2) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and (tmp_101_i_reg_197 = ap_const_lv1_0)))) then 
            wrk_dst_mat_data_stream_1_V_blk_n <= wrk_dst_mat_data_stream_1_V_full_n;
        else 
            wrk_dst_mat_data_stream_1_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    wrk_dst_mat_data_stream_1_V_din_assign_proc : process(wrk_mats_0_data_stream_1_V_dout, wrk_mats_2_data_stream_1_V_dout, tmp_101_i_reg_197, ap_sig_183)
    begin
        if (ap_sig_183) then
            if (not((tmp_101_i_reg_197 = ap_const_lv1_0))) then 
                wrk_dst_mat_data_stream_1_V_din <= wrk_mats_2_data_stream_1_V_dout;
            elsif ((tmp_101_i_reg_197 = ap_const_lv1_0)) then 
                wrk_dst_mat_data_stream_1_V_din <= wrk_mats_0_data_stream_1_V_dout;
            else 
                wrk_dst_mat_data_stream_1_V_din <= "XXXXXXXX";
            end if;
        else 
            wrk_dst_mat_data_stream_1_V_din <= "XXXXXXXX";
        end if; 
    end process;


    wrk_dst_mat_data_stream_1_V_write_assign_proc : process(ap_sig_cseq_ST_pp0_stg0_fsm_2, ap_reg_ppiten_pp0_it1, tmp_101_i_reg_197, ap_sig_151)
    begin
        if ((((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_2) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and (tmp_101_i_reg_197 = ap_const_lv1_0) and not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and ap_sig_151))) or ((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_2) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and not((tmp_101_i_reg_197 = ap_const_lv1_0)) and not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and ap_sig_151))))) then 
            wrk_dst_mat_data_stream_1_V_write <= ap_const_logic_1;
        else 
            wrk_dst_mat_data_stream_1_V_write <= ap_const_logic_0;
        end if; 
    end process;


    wrk_dst_mat_data_stream_2_V_blk_n_assign_proc : process(wrk_dst_mat_data_stream_2_V_full_n, ap_sig_cseq_ST_pp0_stg0_fsm_2, ap_reg_ppiten_pp0_it1, tmp_101_i_reg_197)
    begin
        if ((((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_2) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and not((tmp_101_i_reg_197 = ap_const_lv1_0))) or ((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_2) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and (tmp_101_i_reg_197 = ap_const_lv1_0)))) then 
            wrk_dst_mat_data_stream_2_V_blk_n <= wrk_dst_mat_data_stream_2_V_full_n;
        else 
            wrk_dst_mat_data_stream_2_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    wrk_dst_mat_data_stream_2_V_din_assign_proc : process(wrk_mats_0_data_stream_2_V_dout, wrk_mats_2_data_stream_2_V_dout, tmp_101_i_reg_197, ap_sig_183)
    begin
        if (ap_sig_183) then
            if (not((tmp_101_i_reg_197 = ap_const_lv1_0))) then 
                wrk_dst_mat_data_stream_2_V_din <= wrk_mats_2_data_stream_2_V_dout;
            elsif ((tmp_101_i_reg_197 = ap_const_lv1_0)) then 
                wrk_dst_mat_data_stream_2_V_din <= wrk_mats_0_data_stream_2_V_dout;
            else 
                wrk_dst_mat_data_stream_2_V_din <= "XXXXXXXX";
            end if;
        else 
            wrk_dst_mat_data_stream_2_V_din <= "XXXXXXXX";
        end if; 
    end process;


    wrk_dst_mat_data_stream_2_V_write_assign_proc : process(ap_sig_cseq_ST_pp0_stg0_fsm_2, ap_reg_ppiten_pp0_it1, tmp_101_i_reg_197, ap_sig_151)
    begin
        if ((((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_2) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and (tmp_101_i_reg_197 = ap_const_lv1_0) and not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and ap_sig_151))) or ((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_2) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and not((tmp_101_i_reg_197 = ap_const_lv1_0)) and not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and ap_sig_151))))) then 
            wrk_dst_mat_data_stream_2_V_write <= ap_const_logic_1;
        else 
            wrk_dst_mat_data_stream_2_V_write <= ap_const_logic_0;
        end if; 
    end process;


    wrk_mats_0_data_stream_0_V_blk_n_assign_proc : process(wrk_mats_0_data_stream_0_V_empty_n, ap_sig_cseq_ST_pp0_stg0_fsm_2, ap_reg_ppiten_pp0_it1)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_2) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1))) then 
            wrk_mats_0_data_stream_0_V_blk_n <= wrk_mats_0_data_stream_0_V_empty_n;
        else 
            wrk_mats_0_data_stream_0_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    wrk_mats_0_data_stream_0_V_read_assign_proc : process(ap_sig_cseq_ST_pp0_stg0_fsm_2, ap_reg_ppiten_pp0_it1, ap_sig_151)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_2) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and ap_sig_151)))) then 
            wrk_mats_0_data_stream_0_V_read <= ap_const_logic_1;
        else 
            wrk_mats_0_data_stream_0_V_read <= ap_const_logic_0;
        end if; 
    end process;


    wrk_mats_0_data_stream_1_V_blk_n_assign_proc : process(wrk_mats_0_data_stream_1_V_empty_n, ap_sig_cseq_ST_pp0_stg0_fsm_2, ap_reg_ppiten_pp0_it1)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_2) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1))) then 
            wrk_mats_0_data_stream_1_V_blk_n <= wrk_mats_0_data_stream_1_V_empty_n;
        else 
            wrk_mats_0_data_stream_1_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    wrk_mats_0_data_stream_1_V_read_assign_proc : process(ap_sig_cseq_ST_pp0_stg0_fsm_2, ap_reg_ppiten_pp0_it1, ap_sig_151)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_2) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and ap_sig_151)))) then 
            wrk_mats_0_data_stream_1_V_read <= ap_const_logic_1;
        else 
            wrk_mats_0_data_stream_1_V_read <= ap_const_logic_0;
        end if; 
    end process;


    wrk_mats_0_data_stream_2_V_blk_n_assign_proc : process(wrk_mats_0_data_stream_2_V_empty_n, ap_sig_cseq_ST_pp0_stg0_fsm_2, ap_reg_ppiten_pp0_it1)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_2) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1))) then 
            wrk_mats_0_data_stream_2_V_blk_n <= wrk_mats_0_data_stream_2_V_empty_n;
        else 
            wrk_mats_0_data_stream_2_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    wrk_mats_0_data_stream_2_V_read_assign_proc : process(ap_sig_cseq_ST_pp0_stg0_fsm_2, ap_reg_ppiten_pp0_it1, ap_sig_151)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_2) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and ap_sig_151)))) then 
            wrk_mats_0_data_stream_2_V_read <= ap_const_logic_1;
        else 
            wrk_mats_0_data_stream_2_V_read <= ap_const_logic_0;
        end if; 
    end process;


    wrk_mats_2_data_stream_0_V_blk_n_assign_proc : process(wrk_mats_2_data_stream_0_V_empty_n, ap_sig_cseq_ST_pp0_stg0_fsm_2, ap_reg_ppiten_pp0_it1)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_2) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1))) then 
            wrk_mats_2_data_stream_0_V_blk_n <= wrk_mats_2_data_stream_0_V_empty_n;
        else 
            wrk_mats_2_data_stream_0_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    wrk_mats_2_data_stream_0_V_read_assign_proc : process(ap_sig_cseq_ST_pp0_stg0_fsm_2, ap_reg_ppiten_pp0_it1, ap_sig_151)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_2) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and ap_sig_151)))) then 
            wrk_mats_2_data_stream_0_V_read <= ap_const_logic_1;
        else 
            wrk_mats_2_data_stream_0_V_read <= ap_const_logic_0;
        end if; 
    end process;


    wrk_mats_2_data_stream_1_V_blk_n_assign_proc : process(wrk_mats_2_data_stream_1_V_empty_n, ap_sig_cseq_ST_pp0_stg0_fsm_2, ap_reg_ppiten_pp0_it1)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_2) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1))) then 
            wrk_mats_2_data_stream_1_V_blk_n <= wrk_mats_2_data_stream_1_V_empty_n;
        else 
            wrk_mats_2_data_stream_1_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    wrk_mats_2_data_stream_1_V_read_assign_proc : process(ap_sig_cseq_ST_pp0_stg0_fsm_2, ap_reg_ppiten_pp0_it1, ap_sig_151)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_2) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and ap_sig_151)))) then 
            wrk_mats_2_data_stream_1_V_read <= ap_const_logic_1;
        else 
            wrk_mats_2_data_stream_1_V_read <= ap_const_logic_0;
        end if; 
    end process;


    wrk_mats_2_data_stream_2_V_blk_n_assign_proc : process(wrk_mats_2_data_stream_2_V_empty_n, ap_sig_cseq_ST_pp0_stg0_fsm_2, ap_reg_ppiten_pp0_it1)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_2) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1))) then 
            wrk_mats_2_data_stream_2_V_blk_n <= wrk_mats_2_data_stream_2_V_empty_n;
        else 
            wrk_mats_2_data_stream_2_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    wrk_mats_2_data_stream_2_V_read_assign_proc : process(ap_sig_cseq_ST_pp0_stg0_fsm_2, ap_reg_ppiten_pp0_it1, ap_sig_151)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_2) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and ap_sig_151)))) then 
            wrk_mats_2_data_stream_2_V_read <= ap_const_logic_1;
        else 
            wrk_mats_2_data_stream_2_V_read <= ap_const_logic_0;
        end if; 
    end process;

end behav;
