# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /opt/Xilinx/Projects/zybo_petalinux_video_hls/zybo_petalinux_video_hls.srcs/sources_1/bd/block_design_0/ip/block_design_0_auto_us_0/block_design_0_auto_us_0.xci
# IP: The module: 'block_design_0_auto_us_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /opt/Xilinx/Projects/zybo_petalinux_video_hls/zybo_petalinux_video_hls.srcs/sources_1/bd/block_design_0/ip/block_design_0_auto_us_0/block_design_0_auto_us_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_design_0_auto_us_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /opt/Xilinx/Projects/zybo_petalinux_video_hls/zybo_petalinux_video_hls.srcs/sources_1/bd/block_design_0/ip/block_design_0_auto_us_0/block_design_0_auto_us_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_design_0_auto_us_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /opt/Xilinx/Projects/zybo_petalinux_video_hls/zybo_petalinux_video_hls.srcs/sources_1/bd/block_design_0/ip/block_design_0_auto_us_0/block_design_0_auto_us_0.xci
# IP: The module: 'block_design_0_auto_us_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /opt/Xilinx/Projects/zybo_petalinux_video_hls/zybo_petalinux_video_hls.srcs/sources_1/bd/block_design_0/ip/block_design_0_auto_us_0/block_design_0_auto_us_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_design_0_auto_us_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /opt/Xilinx/Projects/zybo_petalinux_video_hls/zybo_petalinux_video_hls.srcs/sources_1/bd/block_design_0/ip/block_design_0_auto_us_0/block_design_0_auto_us_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_design_0_auto_us_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
