// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xfilt.h"

extern XFilt_Config XFilt_ConfigTable[];

XFilt_Config *XFilt_LookupConfig(u16 DeviceId) {
	XFilt_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XFILT_NUM_INSTANCES; Index++) {
		if (XFilt_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XFilt_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XFilt_Initialize(XFilt *InstancePtr, u16 DeviceId) {
	XFilt_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XFilt_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XFilt_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

