-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2016.2
-- Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity filt_Mat2AXIvideo is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    img_rows_V_dout : IN STD_LOGIC_VECTOR (9 downto 0);
    img_rows_V_empty_n : IN STD_LOGIC;
    img_rows_V_read : OUT STD_LOGIC;
    img_cols_V_dout : IN STD_LOGIC_VECTOR (10 downto 0);
    img_cols_V_empty_n : IN STD_LOGIC;
    img_cols_V_read : OUT STD_LOGIC;
    img_data_stream_0_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    img_data_stream_0_V_empty_n : IN STD_LOGIC;
    img_data_stream_0_V_read : OUT STD_LOGIC;
    img_data_stream_1_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    img_data_stream_1_V_empty_n : IN STD_LOGIC;
    img_data_stream_1_V_read : OUT STD_LOGIC;
    img_data_stream_2_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    img_data_stream_2_V_empty_n : IN STD_LOGIC;
    img_data_stream_2_V_read : OUT STD_LOGIC;
    img_data_stream_3_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    img_data_stream_3_V_empty_n : IN STD_LOGIC;
    img_data_stream_3_V_read : OUT STD_LOGIC;
    dst_axi_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    dst_axi_TVALID : OUT STD_LOGIC;
    dst_axi_TREADY : IN STD_LOGIC;
    dst_axi_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    dst_axi_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    dst_axi_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    dst_axi_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    dst_axi_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    dst_axi_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of filt_Mat2AXIvideo is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_st1_fsm_0 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_st2_fsm_1 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_pp0_stg0_fsm_2 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_st5_fsm_3 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv11_7FF : STD_LOGIC_VECTOR (10 downto 0) := "11111111111";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_sig_cseq_ST_st1_fsm_0 : STD_LOGIC;
    signal ap_sig_22 : BOOLEAN;
    signal img_rows_V_blk_n : STD_LOGIC;
    signal img_cols_V_blk_n : STD_LOGIC;
    signal img_data_stream_0_V_blk_n : STD_LOGIC;
    signal ap_sig_cseq_ST_pp0_stg0_fsm_2 : STD_LOGIC;
    signal ap_sig_75 : BOOLEAN;
    signal ap_reg_ppiten_pp0_it1 : STD_LOGIC := '0';
    signal ap_reg_ppiten_pp0_it0 : STD_LOGIC := '0';
    signal exitcond5_i_reg_290 : STD_LOGIC_VECTOR (0 downto 0);
    signal img_data_stream_1_V_blk_n : STD_LOGIC;
    signal img_data_stream_2_V_blk_n : STD_LOGIC;
    signal img_data_stream_3_V_blk_n : STD_LOGIC;
    signal dst_axi_TDATA_blk_n : STD_LOGIC;
    signal p_3_i_reg_180 : STD_LOGIC_VECTOR (9 downto 0);
    signal img_rows_V_read_reg_266 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_sig_99 : BOOLEAN;
    signal img_cols_V_read_reg_271 : STD_LOGIC_VECTOR (10 downto 0);
    signal r_V_fu_191_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal r_V_reg_276 : STD_LOGIC_VECTOR (10 downto 0);
    signal exitcond4_i_fu_206_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_cseq_ST_st2_fsm_1 : STD_LOGIC;
    signal ap_sig_113 : BOOLEAN;
    signal i_V_fu_211_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal i_V_reg_285 : STD_LOGIC_VECTOR (8 downto 0);
    signal exitcond5_i_fu_221_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_129 : BOOLEAN;
    signal ap_sig_ioackin_dst_axi_TREADY : STD_LOGIC;
    signal j_V_fu_226_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal axi_last_V_fu_232_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal axi_last_V_reg_299 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_i_reg_169 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_sig_cseq_ST_st5_fsm_3 : STD_LOGIC;
    signal ap_sig_157 : BOOLEAN;
    signal tmp_user_V_fu_100 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ioackin_dst_axi_TREADY : STD_LOGIC := '0';
    signal p_cast_cast_i_fu_202_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_3_cast_cast_i_fu_217_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_st1_fsm_0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_continue)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and not((ap_const_lv1_0 = exitcond4_i_fu_206_p2)))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_reg_ioackin_dst_axi_TREADY_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ioackin_dst_axi_TREADY <= ap_const_logic_0;
            else
                if ((((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_2) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and (exitcond5_i_reg_290 = ap_const_lv1_0) and not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and (ap_sig_129 or ((exitcond5_i_reg_290 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_dst_axi_TREADY)))))))) then 
                    ap_reg_ioackin_dst_axi_TREADY <= ap_const_logic_0;
                elsif ((((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_2) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and (exitcond5_i_reg_290 = ap_const_lv1_0) and not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and ap_sig_129)) and (ap_const_logic_1 = dst_axi_TREADY)))) then 
                    ap_reg_ioackin_dst_axi_TREADY <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_reg_ppiten_pp0_it0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_2) and not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and (ap_sig_129 or ((exitcond5_i_reg_290 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_dst_axi_TREADY))))) and not((ap_const_lv1_0 = exitcond5_i_fu_221_p2)))) then 
                    ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and (ap_const_lv1_0 = exitcond4_i_fu_206_p2))) then 
                    ap_reg_ppiten_pp0_it0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_reg_ppiten_pp0_it1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_2) and not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and (ap_sig_129 or ((exitcond5_i_reg_290 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_dst_axi_TREADY))))) and (ap_const_lv1_0 = exitcond5_i_fu_221_p2))) then 
                    ap_reg_ppiten_pp0_it1 <= ap_const_logic_1;
                elsif ((((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and (ap_const_lv1_0 = exitcond4_i_fu_206_p2)) or ((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_2) and not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and (ap_sig_129 or ((exitcond5_i_reg_290 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_dst_axi_TREADY))))) and not((ap_const_lv1_0 = exitcond5_i_fu_221_p2))))) then 
                    ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    p_3_i_reg_180_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_2) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and (ap_sig_129 or ((exitcond5_i_reg_290 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_dst_axi_TREADY))))) and (ap_const_lv1_0 = exitcond5_i_fu_221_p2))) then 
                p_3_i_reg_180 <= j_V_fu_226_p2;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and (ap_const_lv1_0 = exitcond4_i_fu_206_p2))) then 
                p_3_i_reg_180 <= ap_const_lv10_0;
            end if; 
        end if;
    end process;

    p_i_reg_169_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not(ap_sig_99))) then 
                p_i_reg_169 <= ap_const_lv9_0;
            elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st5_fsm_3)) then 
                p_i_reg_169 <= i_V_reg_285;
            end if; 
        end if;
    end process;

    tmp_user_V_fu_100_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_2) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and (exitcond5_i_reg_290 = ap_const_lv1_0) and not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and (ap_sig_129 or ((exitcond5_i_reg_290 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_dst_axi_TREADY))))))) then 
                tmp_user_V_fu_100 <= ap_const_lv1_0;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not(ap_sig_99))) then 
                tmp_user_V_fu_100 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_2) and not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and (ap_sig_129 or ((exitcond5_i_reg_290 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_dst_axi_TREADY))))) and (ap_const_lv1_0 = exitcond5_i_fu_221_p2))) then
                axi_last_V_reg_299 <= axi_last_V_fu_232_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_2) and not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and (ap_sig_129 or ((exitcond5_i_reg_290 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_dst_axi_TREADY))))))) then
                exitcond5_i_reg_290 <= exitcond5_i_fu_221_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1)) then
                i_V_reg_285 <= i_V_fu_211_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not(ap_sig_99))) then
                img_cols_V_read_reg_271 <= img_cols_V_dout;
                img_rows_V_read_reg_266 <= img_rows_V_dout;
                r_V_reg_276 <= r_V_fu_191_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_reg_ppiten_pp0_it1, ap_reg_ppiten_pp0_it0, exitcond5_i_reg_290, ap_sig_99, exitcond4_i_fu_206_p2, exitcond5_i_fu_221_p2, ap_sig_129, ap_sig_ioackin_dst_axi_TREADY)
    begin
        case ap_CS_fsm is
            when ap_ST_st1_fsm_0 => 
                if (not(ap_sig_99)) then
                    ap_NS_fsm <= ap_ST_st2_fsm_1;
                else
                    ap_NS_fsm <= ap_ST_st1_fsm_0;
                end if;
            when ap_ST_st2_fsm_1 => 
                if (not((ap_const_lv1_0 = exitcond4_i_fu_206_p2))) then
                    ap_NS_fsm <= ap_ST_st1_fsm_0;
                else
                    ap_NS_fsm <= ap_ST_pp0_stg0_fsm_2;
                end if;
            when ap_ST_pp0_stg0_fsm_2 => 
                if (not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and (ap_sig_129 or ((exitcond5_i_reg_290 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_dst_axi_TREADY))))) and not((ap_const_lv1_0 = exitcond5_i_fu_221_p2))))) then
                    ap_NS_fsm <= ap_ST_pp0_stg0_fsm_2;
                elsif (((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and (ap_sig_129 or ((exitcond5_i_reg_290 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_dst_axi_TREADY))))) and not((ap_const_lv1_0 = exitcond5_i_fu_221_p2)))) then
                    ap_NS_fsm <= ap_ST_st5_fsm_3;
                else
                    ap_NS_fsm <= ap_ST_pp0_stg0_fsm_2;
                end if;
            when ap_ST_st5_fsm_3 => 
                ap_NS_fsm <= ap_ST_st2_fsm_1;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;

    ap_done_assign_proc : process(ap_done_reg, exitcond4_i_fu_206_p2, ap_sig_cseq_ST_st2_fsm_1)
    begin
        if (((ap_const_logic_1 = ap_done_reg) or ((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and not((ap_const_lv1_0 = exitcond4_i_fu_206_p2))))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_sig_cseq_ST_st1_fsm_0)
    begin
        if (((ap_const_logic_0 = ap_start) and (ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(exitcond4_i_fu_206_p2, ap_sig_cseq_ST_st2_fsm_1)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and not((ap_const_lv1_0 = exitcond4_i_fu_206_p2)))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_113_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_113 <= (ap_const_lv1_1 = ap_CS_fsm(1 downto 1));
    end process;


    ap_sig_129_assign_proc : process(img_data_stream_0_V_empty_n, img_data_stream_1_V_empty_n, img_data_stream_2_V_empty_n, img_data_stream_3_V_empty_n, exitcond5_i_reg_290)
    begin
                ap_sig_129 <= (((exitcond5_i_reg_290 = ap_const_lv1_0) and (img_data_stream_0_V_empty_n = ap_const_logic_0)) or ((exitcond5_i_reg_290 = ap_const_lv1_0) and (img_data_stream_1_V_empty_n = ap_const_logic_0)) or ((exitcond5_i_reg_290 = ap_const_lv1_0) and (img_data_stream_2_V_empty_n = ap_const_logic_0)) or ((exitcond5_i_reg_290 = ap_const_lv1_0) and (img_data_stream_3_V_empty_n = ap_const_logic_0)));
    end process;


    ap_sig_157_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_157 <= (ap_const_lv1_1 = ap_CS_fsm(3 downto 3));
    end process;


    ap_sig_22_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_22 <= (ap_CS_fsm(0 downto 0) = ap_const_lv1_1);
    end process;


    ap_sig_75_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_75 <= (ap_const_lv1_1 = ap_CS_fsm(2 downto 2));
    end process;


    ap_sig_99_assign_proc : process(ap_start, ap_done_reg, img_rows_V_empty_n, img_cols_V_empty_n)
    begin
                ap_sig_99 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (img_rows_V_empty_n = ap_const_logic_0) or (img_cols_V_empty_n = ap_const_logic_0));
    end process;


    ap_sig_cseq_ST_pp0_stg0_fsm_2_assign_proc : process(ap_sig_75)
    begin
        if (ap_sig_75) then 
            ap_sig_cseq_ST_pp0_stg0_fsm_2 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_pp0_stg0_fsm_2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st1_fsm_0_assign_proc : process(ap_sig_22)
    begin
        if (ap_sig_22) then 
            ap_sig_cseq_ST_st1_fsm_0 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st1_fsm_0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st2_fsm_1_assign_proc : process(ap_sig_113)
    begin
        if (ap_sig_113) then 
            ap_sig_cseq_ST_st2_fsm_1 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st2_fsm_1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st5_fsm_3_assign_proc : process(ap_sig_157)
    begin
        if (ap_sig_157) then 
            ap_sig_cseq_ST_st5_fsm_3 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st5_fsm_3 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_ioackin_dst_axi_TREADY_assign_proc : process(dst_axi_TREADY, ap_reg_ioackin_dst_axi_TREADY)
    begin
        if ((ap_const_logic_0 = ap_reg_ioackin_dst_axi_TREADY)) then 
            ap_sig_ioackin_dst_axi_TREADY <= dst_axi_TREADY;
        else 
            ap_sig_ioackin_dst_axi_TREADY <= ap_const_logic_1;
        end if; 
    end process;

    axi_last_V_fu_232_p2 <= "1" when (p_3_cast_cast_i_fu_217_p1 = r_V_reg_276) else "0";
    dst_axi_TDATA <= (((img_data_stream_3_V_dout & img_data_stream_2_V_dout) & img_data_stream_1_V_dout) & img_data_stream_0_V_dout);

    dst_axi_TDATA_blk_n_assign_proc : process(dst_axi_TREADY, ap_sig_cseq_ST_pp0_stg0_fsm_2, ap_reg_ppiten_pp0_it1, exitcond5_i_reg_290)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_2) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and (exitcond5_i_reg_290 = ap_const_lv1_0))) then 
            dst_axi_TDATA_blk_n <= dst_axi_TREADY;
        else 
            dst_axi_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    dst_axi_TDEST <= ap_const_lv1_0;
    dst_axi_TID <= ap_const_lv1_0;
    dst_axi_TKEEP <= ap_const_lv4_F;
    dst_axi_TLAST <= axi_last_V_reg_299;
    dst_axi_TSTRB <= ap_const_lv4_0;
    dst_axi_TUSER <= tmp_user_V_fu_100;

    dst_axi_TVALID_assign_proc : process(ap_sig_cseq_ST_pp0_stg0_fsm_2, ap_reg_ppiten_pp0_it1, exitcond5_i_reg_290, ap_sig_129, ap_reg_ioackin_dst_axi_TREADY)
    begin
        if ((((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_2) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and (exitcond5_i_reg_290 = ap_const_lv1_0) and not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and ap_sig_129)) and (ap_const_logic_0 = ap_reg_ioackin_dst_axi_TREADY)))) then 
            dst_axi_TVALID <= ap_const_logic_1;
        else 
            dst_axi_TVALID <= ap_const_logic_0;
        end if; 
    end process;

    exitcond4_i_fu_206_p2 <= "1" when (p_cast_cast_i_fu_202_p1 = img_rows_V_read_reg_266) else "0";
    exitcond5_i_fu_221_p2 <= "1" when (p_3_cast_cast_i_fu_217_p1 = img_cols_V_read_reg_271) else "0";
    i_V_fu_211_p2 <= std_logic_vector(unsigned(p_i_reg_169) + unsigned(ap_const_lv9_1));

    img_cols_V_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_sig_cseq_ST_st1_fsm_0, img_cols_V_empty_n)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))))) then 
            img_cols_V_blk_n <= img_cols_V_empty_n;
        else 
            img_cols_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    img_cols_V_read_assign_proc : process(ap_sig_cseq_ST_st1_fsm_0, ap_sig_99)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not(ap_sig_99))) then 
            img_cols_V_read <= ap_const_logic_1;
        else 
            img_cols_V_read <= ap_const_logic_0;
        end if; 
    end process;


    img_data_stream_0_V_blk_n_assign_proc : process(img_data_stream_0_V_empty_n, ap_sig_cseq_ST_pp0_stg0_fsm_2, ap_reg_ppiten_pp0_it1, exitcond5_i_reg_290)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_2) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and (exitcond5_i_reg_290 = ap_const_lv1_0))) then 
            img_data_stream_0_V_blk_n <= img_data_stream_0_V_empty_n;
        else 
            img_data_stream_0_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    img_data_stream_0_V_read_assign_proc : process(ap_sig_cseq_ST_pp0_stg0_fsm_2, ap_reg_ppiten_pp0_it1, exitcond5_i_reg_290, ap_sig_129, ap_sig_ioackin_dst_axi_TREADY)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_2) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and (exitcond5_i_reg_290 = ap_const_lv1_0) and not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and (ap_sig_129 or ((exitcond5_i_reg_290 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_dst_axi_TREADY))))))) then 
            img_data_stream_0_V_read <= ap_const_logic_1;
        else 
            img_data_stream_0_V_read <= ap_const_logic_0;
        end if; 
    end process;


    img_data_stream_1_V_blk_n_assign_proc : process(img_data_stream_1_V_empty_n, ap_sig_cseq_ST_pp0_stg0_fsm_2, ap_reg_ppiten_pp0_it1, exitcond5_i_reg_290)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_2) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and (exitcond5_i_reg_290 = ap_const_lv1_0))) then 
            img_data_stream_1_V_blk_n <= img_data_stream_1_V_empty_n;
        else 
            img_data_stream_1_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    img_data_stream_1_V_read_assign_proc : process(ap_sig_cseq_ST_pp0_stg0_fsm_2, ap_reg_ppiten_pp0_it1, exitcond5_i_reg_290, ap_sig_129, ap_sig_ioackin_dst_axi_TREADY)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_2) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and (exitcond5_i_reg_290 = ap_const_lv1_0) and not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and (ap_sig_129 or ((exitcond5_i_reg_290 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_dst_axi_TREADY))))))) then 
            img_data_stream_1_V_read <= ap_const_logic_1;
        else 
            img_data_stream_1_V_read <= ap_const_logic_0;
        end if; 
    end process;


    img_data_stream_2_V_blk_n_assign_proc : process(img_data_stream_2_V_empty_n, ap_sig_cseq_ST_pp0_stg0_fsm_2, ap_reg_ppiten_pp0_it1, exitcond5_i_reg_290)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_2) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and (exitcond5_i_reg_290 = ap_const_lv1_0))) then 
            img_data_stream_2_V_blk_n <= img_data_stream_2_V_empty_n;
        else 
            img_data_stream_2_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    img_data_stream_2_V_read_assign_proc : process(ap_sig_cseq_ST_pp0_stg0_fsm_2, ap_reg_ppiten_pp0_it1, exitcond5_i_reg_290, ap_sig_129, ap_sig_ioackin_dst_axi_TREADY)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_2) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and (exitcond5_i_reg_290 = ap_const_lv1_0) and not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and (ap_sig_129 or ((exitcond5_i_reg_290 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_dst_axi_TREADY))))))) then 
            img_data_stream_2_V_read <= ap_const_logic_1;
        else 
            img_data_stream_2_V_read <= ap_const_logic_0;
        end if; 
    end process;


    img_data_stream_3_V_blk_n_assign_proc : process(img_data_stream_3_V_empty_n, ap_sig_cseq_ST_pp0_stg0_fsm_2, ap_reg_ppiten_pp0_it1, exitcond5_i_reg_290)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_2) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and (exitcond5_i_reg_290 = ap_const_lv1_0))) then 
            img_data_stream_3_V_blk_n <= img_data_stream_3_V_empty_n;
        else 
            img_data_stream_3_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    img_data_stream_3_V_read_assign_proc : process(ap_sig_cseq_ST_pp0_stg0_fsm_2, ap_reg_ppiten_pp0_it1, exitcond5_i_reg_290, ap_sig_129, ap_sig_ioackin_dst_axi_TREADY)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_2) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and (exitcond5_i_reg_290 = ap_const_lv1_0) and not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and (ap_sig_129 or ((exitcond5_i_reg_290 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_dst_axi_TREADY))))))) then 
            img_data_stream_3_V_read <= ap_const_logic_1;
        else 
            img_data_stream_3_V_read <= ap_const_logic_0;
        end if; 
    end process;


    img_rows_V_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_sig_cseq_ST_st1_fsm_0, img_rows_V_empty_n)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))))) then 
            img_rows_V_blk_n <= img_rows_V_empty_n;
        else 
            img_rows_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    img_rows_V_read_assign_proc : process(ap_sig_cseq_ST_st1_fsm_0, ap_sig_99)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not(ap_sig_99))) then 
            img_rows_V_read <= ap_const_logic_1;
        else 
            img_rows_V_read <= ap_const_logic_0;
        end if; 
    end process;

    j_V_fu_226_p2 <= std_logic_vector(unsigned(p_3_i_reg_180) + unsigned(ap_const_lv10_1));
    p_3_cast_cast_i_fu_217_p1 <= std_logic_vector(resize(unsigned(p_3_i_reg_180),11));
    p_cast_cast_i_fu_202_p1 <= std_logic_vector(resize(unsigned(p_i_reg_169),10));
    r_V_fu_191_p2 <= std_logic_vector(unsigned(img_cols_V_dout) + unsigned(ap_const_lv11_7FF));
end behav;
