// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "filt_AXIvideo2Mat.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic filt_AXIvideo2Mat::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic filt_AXIvideo2Mat::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<7> filt_AXIvideo2Mat::ap_ST_st1_fsm_0 = "1";
const sc_lv<7> filt_AXIvideo2Mat::ap_ST_st2_fsm_1 = "10";
const sc_lv<7> filt_AXIvideo2Mat::ap_ST_st3_fsm_2 = "100";
const sc_lv<7> filt_AXIvideo2Mat::ap_ST_st4_fsm_3 = "1000";
const sc_lv<7> filt_AXIvideo2Mat::ap_ST_pp1_stg0_fsm_4 = "10000";
const sc_lv<7> filt_AXIvideo2Mat::ap_ST_st7_fsm_5 = "100000";
const sc_lv<7> filt_AXIvideo2Mat::ap_ST_st8_fsm_6 = "1000000";
const sc_lv<32> filt_AXIvideo2Mat::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> filt_AXIvideo2Mat::ap_const_lv1_1 = "1";
const sc_lv<32> filt_AXIvideo2Mat::ap_const_lv32_1 = "1";
const sc_lv<32> filt_AXIvideo2Mat::ap_const_lv32_4 = "100";
const sc_lv<1> filt_AXIvideo2Mat::ap_const_lv1_0 = "0";
const sc_lv<32> filt_AXIvideo2Mat::ap_const_lv32_5 = "101";
const sc_lv<32> filt_AXIvideo2Mat::ap_const_lv32_3 = "11";
const sc_lv<32> filt_AXIvideo2Mat::ap_const_lv32_6 = "110";
const sc_lv<32> filt_AXIvideo2Mat::ap_const_lv32_2 = "10";
const sc_lv<8> filt_AXIvideo2Mat::ap_const_lv8_0 = "00000000";
const sc_lv<9> filt_AXIvideo2Mat::ap_const_lv9_0 = "000000000";
const sc_lv<8> filt_AXIvideo2Mat::ap_const_lv8_1 = "1";
const sc_lv<9> filt_AXIvideo2Mat::ap_const_lv9_1 = "1";
const sc_lv<32> filt_AXIvideo2Mat::ap_const_lv32_8 = "1000";
const sc_lv<32> filt_AXIvideo2Mat::ap_const_lv32_F = "1111";
const sc_lv<32> filt_AXIvideo2Mat::ap_const_lv32_10 = "10000";
const sc_lv<32> filt_AXIvideo2Mat::ap_const_lv32_17 = "10111";
const sc_lv<32> filt_AXIvideo2Mat::ap_const_lv32_18 = "11000";
const sc_lv<32> filt_AXIvideo2Mat::ap_const_lv32_1F = "11111";
const bool filt_AXIvideo2Mat::ap_true = true;

filt_AXIvideo2Mat::filt_AXIvideo2Mat(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( exitcond6_i_fu_350_p2 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( exitcond6_i_fu_350_p2 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_ap_reg_phiprechg_axi_last_V_2_i_reg_268pp1_it0);

    SC_METHOD(thread_ap_reg_phiprechg_p_Val2_s_reg_281pp1_it0);

    SC_METHOD(thread_ap_sig_106);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_152);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( img_rows_V_empty_n );
    sensitive << ( img_cols_V_empty_n );
    sensitive << ( img_rows_V_out_full_n );
    sensitive << ( img_cols_V_out_full_n );

    SC_METHOD(thread_ap_sig_171);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_176);
    sensitive << ( src_axi_TVALID );
    sensitive << ( exitcond7_i_fu_365_p2 );
    sensitive << ( brmerge_i_fu_379_p2 );

    SC_METHOD(thread_ap_sig_189);
    sensitive << ( img_data_stream_0_V_full_n );
    sensitive << ( img_data_stream_1_V_full_n );
    sensitive << ( img_data_stream_2_V_full_n );
    sensitive << ( img_data_stream_3_V_full_n );
    sensitive << ( exitcond7_i_reg_463 );

    SC_METHOD(thread_ap_sig_197);
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_reg_ppiten_pp1_it0 );
    sensitive << ( ap_reg_ppiten_pp1_it1 );
    sensitive << ( ap_sig_176 );
    sensitive << ( ap_sig_189 );

    SC_METHOD(thread_ap_sig_209);
    sensitive << ( src_axi_TVALID );
    sensitive << ( eol_2_i_reg_317 );

    SC_METHOD(thread_ap_sig_227);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_234);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_25);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_255);
    sensitive << ( exitcond7_i_fu_365_p2 );
    sensitive << ( brmerge_i_fu_379_p2 );

    SC_METHOD(thread_ap_sig_275);
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_reg_ppiten_pp1_it0 );
    sensitive << ( exitcond7_i_fu_365_p2 );

    SC_METHOD(thread_ap_sig_79);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_86);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_99);
    sensitive << ( exitcond7_i_fu_365_p2 );
    sensitive << ( brmerge_i_fu_379_p2 );

    SC_METHOD(thread_ap_sig_cseq_ST_pp1_stg0_fsm_4);
    sensitive << ( ap_sig_86 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_25 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_79 );

    SC_METHOD(thread_ap_sig_cseq_ST_st3_fsm_2);
    sensitive << ( ap_sig_234 );

    SC_METHOD(thread_ap_sig_cseq_ST_st4_fsm_3);
    sensitive << ( ap_sig_171 );

    SC_METHOD(thread_ap_sig_cseq_ST_st7_fsm_5);
    sensitive << ( ap_sig_106 );

    SC_METHOD(thread_ap_sig_cseq_ST_st8_fsm_6);
    sensitive << ( ap_sig_227 );

    SC_METHOD(thread_axi_data_V_1_i_phi_fu_237_p4);
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_reg_ppiten_pp1_it1 );
    sensitive << ( exitcond7_i_reg_463 );
    sensitive << ( axi_data_V_1_i_reg_234 );
    sensitive << ( p_Val2_s_reg_281 );

    SC_METHOD(thread_brmerge_i_fu_379_p2);
    sensitive << ( eol_i_phi_fu_260_p4 );
    sensitive << ( sof_1_i_fu_114 );

    SC_METHOD(thread_eol_i_phi_fu_260_p4);
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_reg_ppiten_pp1_it1 );
    sensitive << ( exitcond7_i_reg_463 );
    sensitive << ( eol_i_reg_256 );
    sensitive << ( axi_last_V_2_i_reg_268 );

    SC_METHOD(thread_eol_phi_fu_226_p4);
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_reg_ppiten_pp1_it1 );
    sensitive << ( exitcond7_i_reg_463 );
    sensitive << ( eol_reg_223 );
    sensitive << ( axi_last_V_2_i_reg_268 );

    SC_METHOD(thread_exitcond6_i_fu_350_p2);
    sensitive << ( img_rows_V_read_reg_424 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( p_cast_cast_i_fu_346_p1 );

    SC_METHOD(thread_exitcond7_i_fu_365_p2);
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_reg_ppiten_pp1_it0 );
    sensitive << ( ap_reg_ppiten_pp1_it1 );
    sensitive << ( img_cols_V_read_reg_429 );
    sensitive << ( ap_sig_176 );
    sensitive << ( ap_sig_189 );
    sensitive << ( p_4_cast_cast_i_fu_361_p1 );

    SC_METHOD(thread_i_V_fu_355_p2);
    sensitive << ( p_i_reg_212 );

    SC_METHOD(thread_img_cols_V_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( img_cols_V_empty_n );

    SC_METHOD(thread_img_cols_V_out_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( img_cols_V_out_full_n );

    SC_METHOD(thread_img_cols_V_out_din);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( img_cols_V_dout );
    sensitive << ( ap_sig_152 );

    SC_METHOD(thread_img_cols_V_out_write);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_152 );

    SC_METHOD(thread_img_cols_V_read);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_152 );

    SC_METHOD(thread_img_data_stream_0_V_blk_n);
    sensitive << ( img_data_stream_0_V_full_n );
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_reg_ppiten_pp1_it1 );
    sensitive << ( exitcond7_i_reg_463 );

    SC_METHOD(thread_img_data_stream_0_V_din);
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_reg_ppiten_pp1_it0 );
    sensitive << ( ap_reg_ppiten_pp1_it1 );
    sensitive << ( exitcond7_i_reg_463 );
    sensitive << ( ap_sig_176 );
    sensitive << ( ap_sig_189 );
    sensitive << ( tmp_reg_476 );

    SC_METHOD(thread_img_data_stream_0_V_write);
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_reg_ppiten_pp1_it0 );
    sensitive << ( ap_reg_ppiten_pp1_it1 );
    sensitive << ( exitcond7_i_reg_463 );
    sensitive << ( ap_sig_176 );
    sensitive << ( ap_sig_189 );

    SC_METHOD(thread_img_data_stream_1_V_blk_n);
    sensitive << ( img_data_stream_1_V_full_n );
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_reg_ppiten_pp1_it1 );
    sensitive << ( exitcond7_i_reg_463 );

    SC_METHOD(thread_img_data_stream_1_V_din);
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_reg_ppiten_pp1_it0 );
    sensitive << ( ap_reg_ppiten_pp1_it1 );
    sensitive << ( exitcond7_i_reg_463 );
    sensitive << ( ap_sig_176 );
    sensitive << ( ap_sig_189 );
    sensitive << ( tmp_108_reg_481 );

    SC_METHOD(thread_img_data_stream_1_V_write);
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_reg_ppiten_pp1_it0 );
    sensitive << ( ap_reg_ppiten_pp1_it1 );
    sensitive << ( exitcond7_i_reg_463 );
    sensitive << ( ap_sig_176 );
    sensitive << ( ap_sig_189 );

    SC_METHOD(thread_img_data_stream_2_V_blk_n);
    sensitive << ( img_data_stream_2_V_full_n );
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_reg_ppiten_pp1_it1 );
    sensitive << ( exitcond7_i_reg_463 );

    SC_METHOD(thread_img_data_stream_2_V_din);
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_reg_ppiten_pp1_it0 );
    sensitive << ( ap_reg_ppiten_pp1_it1 );
    sensitive << ( exitcond7_i_reg_463 );
    sensitive << ( ap_sig_176 );
    sensitive << ( ap_sig_189 );
    sensitive << ( tmp_54_reg_486 );

    SC_METHOD(thread_img_data_stream_2_V_write);
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_reg_ppiten_pp1_it0 );
    sensitive << ( ap_reg_ppiten_pp1_it1 );
    sensitive << ( exitcond7_i_reg_463 );
    sensitive << ( ap_sig_176 );
    sensitive << ( ap_sig_189 );

    SC_METHOD(thread_img_data_stream_3_V_blk_n);
    sensitive << ( img_data_stream_3_V_full_n );
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_reg_ppiten_pp1_it1 );
    sensitive << ( exitcond7_i_reg_463 );

    SC_METHOD(thread_img_data_stream_3_V_din);
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_reg_ppiten_pp1_it0 );
    sensitive << ( ap_reg_ppiten_pp1_it1 );
    sensitive << ( exitcond7_i_reg_463 );
    sensitive << ( ap_sig_176 );
    sensitive << ( ap_sig_189 );
    sensitive << ( tmp_55_reg_491 );

    SC_METHOD(thread_img_data_stream_3_V_write);
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_reg_ppiten_pp1_it0 );
    sensitive << ( ap_reg_ppiten_pp1_it1 );
    sensitive << ( exitcond7_i_reg_463 );
    sensitive << ( ap_sig_176 );
    sensitive << ( ap_sig_189 );

    SC_METHOD(thread_img_rows_V_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( img_rows_V_empty_n );

    SC_METHOD(thread_img_rows_V_out_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( img_rows_V_out_full_n );

    SC_METHOD(thread_img_rows_V_out_din);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( img_rows_V_dout );
    sensitive << ( ap_sig_152 );

    SC_METHOD(thread_img_rows_V_out_write);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_152 );

    SC_METHOD(thread_img_rows_V_read);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_152 );

    SC_METHOD(thread_j_V_fu_370_p2);
    sensitive << ( p_4_i_reg_245 );

    SC_METHOD(thread_p_4_cast_cast_i_fu_361_p1);
    sensitive << ( p_4_i_reg_245 );

    SC_METHOD(thread_p_Val2_s_phi_fu_285_p4);
    sensitive << ( src_axi_TDATA );
    sensitive << ( brmerge_i_fu_379_p2 );
    sensitive << ( axi_data_V_1_i_phi_fu_237_p4 );
    sensitive << ( ap_reg_phiprechg_p_Val2_s_reg_281pp1_it0 );
    sensitive << ( ap_sig_275 );

    SC_METHOD(thread_p_cast_cast_i_fu_346_p1);
    sensitive << ( p_i_reg_212 );

    SC_METHOD(thread_src_axi_TDATA_blk_n);
    sensitive << ( src_axi_TVALID );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_reg_ppiten_pp1_it0 );
    sensitive << ( exitcond7_i_fu_365_p2 );
    sensitive << ( brmerge_i_fu_379_p2 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_5 );
    sensitive << ( eol_2_i_reg_317 );

    SC_METHOD(thread_src_axi_TREADY);
    sensitive << ( src_axi_TVALID );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_reg_ppiten_pp1_it0 );
    sensitive << ( ap_reg_ppiten_pp1_it1 );
    sensitive << ( exitcond7_i_fu_365_p2 );
    sensitive << ( brmerge_i_fu_379_p2 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_5 );
    sensitive << ( ap_sig_176 );
    sensitive << ( ap_sig_189 );
    sensitive << ( ap_sig_209 );
    sensitive << ( eol_2_i_reg_317 );

    SC_METHOD(thread_tmp_fu_385_p1);
    sensitive << ( p_Val2_s_phi_fu_285_p4 );

    SC_METHOD(thread_tmp_user_V_fu_337_p1);
    sensitive << ( src_axi_TUSER );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( src_axi_TVALID );
    sensitive << ( ap_reg_ppiten_pp1_it0 );
    sensitive << ( ap_reg_ppiten_pp1_it1 );
    sensitive << ( exitcond7_i_fu_365_p2 );
    sensitive << ( ap_sig_152 );
    sensitive << ( exitcond6_i_fu_350_p2 );
    sensitive << ( ap_sig_176 );
    sensitive << ( ap_sig_189 );
    sensitive << ( ap_sig_209 );
    sensitive << ( eol_2_i_reg_317 );
    sensitive << ( tmp_user_V_fu_337_p1 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "0000001";
    ap_reg_ppiten_pp1_it0 = SC_LOGIC_0;
    ap_reg_ppiten_pp1_it1 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "filt_AXIvideo2Mat_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, src_axi_TDATA, "(port)src_axi_TDATA");
    sc_trace(mVcdFile, src_axi_TVALID, "(port)src_axi_TVALID");
    sc_trace(mVcdFile, src_axi_TREADY, "(port)src_axi_TREADY");
    sc_trace(mVcdFile, src_axi_TKEEP, "(port)src_axi_TKEEP");
    sc_trace(mVcdFile, src_axi_TSTRB, "(port)src_axi_TSTRB");
    sc_trace(mVcdFile, src_axi_TUSER, "(port)src_axi_TUSER");
    sc_trace(mVcdFile, src_axi_TLAST, "(port)src_axi_TLAST");
    sc_trace(mVcdFile, src_axi_TID, "(port)src_axi_TID");
    sc_trace(mVcdFile, src_axi_TDEST, "(port)src_axi_TDEST");
    sc_trace(mVcdFile, img_rows_V_dout, "(port)img_rows_V_dout");
    sc_trace(mVcdFile, img_rows_V_empty_n, "(port)img_rows_V_empty_n");
    sc_trace(mVcdFile, img_rows_V_read, "(port)img_rows_V_read");
    sc_trace(mVcdFile, img_cols_V_dout, "(port)img_cols_V_dout");
    sc_trace(mVcdFile, img_cols_V_empty_n, "(port)img_cols_V_empty_n");
    sc_trace(mVcdFile, img_cols_V_read, "(port)img_cols_V_read");
    sc_trace(mVcdFile, img_data_stream_0_V_din, "(port)img_data_stream_0_V_din");
    sc_trace(mVcdFile, img_data_stream_0_V_full_n, "(port)img_data_stream_0_V_full_n");
    sc_trace(mVcdFile, img_data_stream_0_V_write, "(port)img_data_stream_0_V_write");
    sc_trace(mVcdFile, img_data_stream_1_V_din, "(port)img_data_stream_1_V_din");
    sc_trace(mVcdFile, img_data_stream_1_V_full_n, "(port)img_data_stream_1_V_full_n");
    sc_trace(mVcdFile, img_data_stream_1_V_write, "(port)img_data_stream_1_V_write");
    sc_trace(mVcdFile, img_data_stream_2_V_din, "(port)img_data_stream_2_V_din");
    sc_trace(mVcdFile, img_data_stream_2_V_full_n, "(port)img_data_stream_2_V_full_n");
    sc_trace(mVcdFile, img_data_stream_2_V_write, "(port)img_data_stream_2_V_write");
    sc_trace(mVcdFile, img_data_stream_3_V_din, "(port)img_data_stream_3_V_din");
    sc_trace(mVcdFile, img_data_stream_3_V_full_n, "(port)img_data_stream_3_V_full_n");
    sc_trace(mVcdFile, img_data_stream_3_V_write, "(port)img_data_stream_3_V_write");
    sc_trace(mVcdFile, img_rows_V_out_din, "(port)img_rows_V_out_din");
    sc_trace(mVcdFile, img_rows_V_out_full_n, "(port)img_rows_V_out_full_n");
    sc_trace(mVcdFile, img_rows_V_out_write, "(port)img_rows_V_out_write");
    sc_trace(mVcdFile, img_cols_V_out_din, "(port)img_cols_V_out_din");
    sc_trace(mVcdFile, img_cols_V_out_full_n, "(port)img_cols_V_out_full_n");
    sc_trace(mVcdFile, img_cols_V_out_write, "(port)img_cols_V_out_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_25, "ap_sig_25");
    sc_trace(mVcdFile, src_axi_TDATA_blk_n, "src_axi_TDATA_blk_n");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_79, "ap_sig_79");
    sc_trace(mVcdFile, ap_sig_cseq_ST_pp1_stg0_fsm_4, "ap_sig_cseq_ST_pp1_stg0_fsm_4");
    sc_trace(mVcdFile, ap_sig_86, "ap_sig_86");
    sc_trace(mVcdFile, ap_reg_ppiten_pp1_it0, "ap_reg_ppiten_pp1_it0");
    sc_trace(mVcdFile, ap_reg_ppiten_pp1_it1, "ap_reg_ppiten_pp1_it1");
    sc_trace(mVcdFile, exitcond7_i_fu_365_p2, "exitcond7_i_fu_365_p2");
    sc_trace(mVcdFile, brmerge_i_fu_379_p2, "brmerge_i_fu_379_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st7_fsm_5, "ap_sig_cseq_ST_st7_fsm_5");
    sc_trace(mVcdFile, ap_sig_106, "ap_sig_106");
    sc_trace(mVcdFile, img_rows_V_blk_n, "img_rows_V_blk_n");
    sc_trace(mVcdFile, img_cols_V_blk_n, "img_cols_V_blk_n");
    sc_trace(mVcdFile, img_data_stream_0_V_blk_n, "img_data_stream_0_V_blk_n");
    sc_trace(mVcdFile, exitcond7_i_reg_463, "exitcond7_i_reg_463");
    sc_trace(mVcdFile, img_data_stream_1_V_blk_n, "img_data_stream_1_V_blk_n");
    sc_trace(mVcdFile, img_data_stream_2_V_blk_n, "img_data_stream_2_V_blk_n");
    sc_trace(mVcdFile, img_data_stream_3_V_blk_n, "img_data_stream_3_V_blk_n");
    sc_trace(mVcdFile, img_rows_V_out_blk_n, "img_rows_V_out_blk_n");
    sc_trace(mVcdFile, img_cols_V_out_blk_n, "img_cols_V_out_blk_n");
    sc_trace(mVcdFile, eol_reg_223, "eol_reg_223");
    sc_trace(mVcdFile, axi_data_V_1_i_reg_234, "axi_data_V_1_i_reg_234");
    sc_trace(mVcdFile, p_4_i_reg_245, "p_4_i_reg_245");
    sc_trace(mVcdFile, eol_i_reg_256, "eol_i_reg_256");
    sc_trace(mVcdFile, axi_last_V_2_i_reg_268, "axi_last_V_2_i_reg_268");
    sc_trace(mVcdFile, p_Val2_s_reg_281, "p_Val2_s_reg_281");
    sc_trace(mVcdFile, img_rows_V_read_reg_424, "img_rows_V_read_reg_424");
    sc_trace(mVcdFile, ap_sig_152, "ap_sig_152");
    sc_trace(mVcdFile, img_cols_V_read_reg_429, "img_cols_V_read_reg_429");
    sc_trace(mVcdFile, tmp_data_V_reg_434, "tmp_data_V_reg_434");
    sc_trace(mVcdFile, tmp_last_V_reg_442, "tmp_last_V_reg_442");
    sc_trace(mVcdFile, exitcond6_i_fu_350_p2, "exitcond6_i_fu_350_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st4_fsm_3, "ap_sig_cseq_ST_st4_fsm_3");
    sc_trace(mVcdFile, ap_sig_171, "ap_sig_171");
    sc_trace(mVcdFile, i_V_fu_355_p2, "i_V_fu_355_p2");
    sc_trace(mVcdFile, i_V_reg_458, "i_V_reg_458");
    sc_trace(mVcdFile, ap_sig_176, "ap_sig_176");
    sc_trace(mVcdFile, ap_sig_189, "ap_sig_189");
    sc_trace(mVcdFile, j_V_fu_370_p2, "j_V_fu_370_p2");
    sc_trace(mVcdFile, tmp_fu_385_p1, "tmp_fu_385_p1");
    sc_trace(mVcdFile, tmp_reg_476, "tmp_reg_476");
    sc_trace(mVcdFile, tmp_108_reg_481, "tmp_108_reg_481");
    sc_trace(mVcdFile, tmp_54_reg_486, "tmp_54_reg_486");
    sc_trace(mVcdFile, tmp_55_reg_491, "tmp_55_reg_491");
    sc_trace(mVcdFile, ap_sig_209, "ap_sig_209");
    sc_trace(mVcdFile, axi_last_V_3_i_reg_293, "axi_last_V_3_i_reg_293");
    sc_trace(mVcdFile, axi_last_V1_i_reg_192, "axi_last_V1_i_reg_192");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st8_fsm_6, "ap_sig_cseq_ST_st8_fsm_6");
    sc_trace(mVcdFile, ap_sig_227, "ap_sig_227");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st3_fsm_2, "ap_sig_cseq_ST_st3_fsm_2");
    sc_trace(mVcdFile, ap_sig_234, "ap_sig_234");
    sc_trace(mVcdFile, axi_data_V_3_i_reg_305, "axi_data_V_3_i_reg_305");
    sc_trace(mVcdFile, axi_data_V1_i_reg_202, "axi_data_V1_i_reg_202");
    sc_trace(mVcdFile, p_i_reg_212, "p_i_reg_212");
    sc_trace(mVcdFile, eol_phi_fu_226_p4, "eol_phi_fu_226_p4");
    sc_trace(mVcdFile, axi_data_V_1_i_phi_fu_237_p4, "axi_data_V_1_i_phi_fu_237_p4");
    sc_trace(mVcdFile, eol_i_phi_fu_260_p4, "eol_i_phi_fu_260_p4");
    sc_trace(mVcdFile, ap_reg_phiprechg_axi_last_V_2_i_reg_268pp1_it0, "ap_reg_phiprechg_axi_last_V_2_i_reg_268pp1_it0");
    sc_trace(mVcdFile, ap_reg_phiprechg_p_Val2_s_reg_281pp1_it0, "ap_reg_phiprechg_p_Val2_s_reg_281pp1_it0");
    sc_trace(mVcdFile, p_Val2_s_phi_fu_285_p4, "p_Val2_s_phi_fu_285_p4");
    sc_trace(mVcdFile, eol_2_i_reg_317, "eol_2_i_reg_317");
    sc_trace(mVcdFile, sof_1_i_fu_114, "sof_1_i_fu_114");
    sc_trace(mVcdFile, p_cast_cast_i_fu_346_p1, "p_cast_cast_i_fu_346_p1");
    sc_trace(mVcdFile, p_4_cast_cast_i_fu_361_p1, "p_4_cast_cast_i_fu_361_p1");
    sc_trace(mVcdFile, tmp_user_V_fu_337_p1, "tmp_user_V_fu_337_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_sig_99, "ap_sig_99");
    sc_trace(mVcdFile, ap_sig_255, "ap_sig_255");
    sc_trace(mVcdFile, ap_sig_197, "ap_sig_197");
    sc_trace(mVcdFile, ap_sig_275, "ap_sig_275");
#endif

    }
}

filt_AXIvideo2Mat::~filt_AXIvideo2Mat() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void filt_AXIvideo2Mat::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
                    !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond6_i_fu_350_p2.read()))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp1_it0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
             !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
  ap_sig_176.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
  ap_sig_189.read())) && 
             !esl_seteq<1,1,1>(exitcond7_i_fu_365_p2.read(), ap_const_lv1_0))) {
            ap_reg_ppiten_pp1_it0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, exitcond6_i_fu_350_p2.read()))) {
            ap_reg_ppiten_pp1_it0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp1_it1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
             esl_seteq<1,1,1>(exitcond7_i_fu_365_p2.read(), ap_const_lv1_0) && 
             !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
  ap_sig_176.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
  ap_sig_189.read())))) {
            ap_reg_ppiten_pp1_it1 = ap_const_logic_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
                     esl_seteq<1,1,1>(ap_const_lv1_0, exitcond6_i_fu_350_p2.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
                     !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
  ap_sig_176.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
  ap_sig_189.read())) && 
                     !esl_seteq<1,1,1>(exitcond7_i_fu_365_p2.read(), ap_const_lv1_0)))) {
            ap_reg_ppiten_pp1_it1 = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        axi_data_V1_i_reg_202 = tmp_data_V_reg_434.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_6.read())) {
        axi_data_V1_i_reg_202 = axi_data_V_3_i_reg_305.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond7_i_reg_463.read()) && 
         !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
  ap_sig_176.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
  ap_sig_189.read())))) {
        axi_data_V_1_i_reg_234 = p_Val2_s_reg_281.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond6_i_fu_350_p2.read()))) {
        axi_data_V_1_i_reg_234 = axi_data_V1_i_reg_202.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
         !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
  ap_sig_176.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
  ap_sig_189.read())) && 
         !esl_seteq<1,1,1>(exitcond7_i_fu_365_p2.read(), ap_const_lv1_0))) {
        axi_data_V_3_i_reg_305 = axi_data_V_1_i_phi_fu_237_p4.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_5.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_i_reg_317.read()) && 
                !ap_sig_209.read())) {
        axi_data_V_3_i_reg_305 = src_axi_TDATA.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        axi_last_V1_i_reg_192 = tmp_last_V_reg_442.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_6.read())) {
        axi_last_V1_i_reg_192 = axi_last_V_3_i_reg_293.read();
    }
    if (ap_sig_197.read()) {
        if (ap_sig_255.read()) {
            axi_last_V_2_i_reg_268 = eol_phi_fu_226_p4.read();
        } else if (ap_sig_99.read()) {
            axi_last_V_2_i_reg_268 = src_axi_TLAST.read();
        } else if (esl_seteq<1,1,1>(ap_true, ap_true)) {
            axi_last_V_2_i_reg_268 = ap_reg_phiprechg_axi_last_V_2_i_reg_268pp1_it0.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
         !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
  ap_sig_176.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
  ap_sig_189.read())) && 
         !esl_seteq<1,1,1>(exitcond7_i_fu_365_p2.read(), ap_const_lv1_0))) {
        axi_last_V_3_i_reg_293 = eol_phi_fu_226_p4.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_5.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_i_reg_317.read()) && 
                !ap_sig_209.read())) {
        axi_last_V_3_i_reg_293 = src_axi_TLAST.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
         !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
  ap_sig_176.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
  ap_sig_189.read())) && 
         !esl_seteq<1,1,1>(exitcond7_i_fu_365_p2.read(), ap_const_lv1_0))) {
        eol_2_i_reg_317 = eol_i_phi_fu_260_p4.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_5.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_i_reg_317.read()) && 
                !ap_sig_209.read())) {
        eol_2_i_reg_317 = src_axi_TLAST.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond7_i_reg_463.read()) && 
         !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
  ap_sig_176.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
  ap_sig_189.read())))) {
        eol_i_reg_256 = axi_last_V_2_i_reg_268.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond6_i_fu_350_p2.read()))) {
        eol_i_reg_256 = ap_const_lv1_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond7_i_reg_463.read()) && 
         !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
  ap_sig_176.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
  ap_sig_189.read())))) {
        eol_reg_223 = axi_last_V_2_i_reg_268.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond6_i_fu_350_p2.read()))) {
        eol_reg_223 = axi_last_V1_i_reg_192.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
         esl_seteq<1,1,1>(exitcond7_i_fu_365_p2.read(), ap_const_lv1_0) && 
         !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
  ap_sig_176.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
  ap_sig_189.read())))) {
        p_4_i_reg_245 = j_V_fu_370_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond6_i_fu_350_p2.read()))) {
        p_4_i_reg_245 = ap_const_lv9_0;
    }
    if (ap_sig_197.read()) {
        if (ap_sig_255.read()) {
            p_Val2_s_reg_281 = axi_data_V_1_i_phi_fu_237_p4.read();
        } else if (ap_sig_99.read()) {
            p_Val2_s_reg_281 = src_axi_TDATA.read();
        } else if (esl_seteq<1,1,1>(ap_true, ap_true)) {
            p_Val2_s_reg_281 = ap_reg_phiprechg_p_Val2_s_reg_281pp1_it0.read();
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        p_i_reg_212 = ap_const_lv8_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_6.read())) {
        p_i_reg_212 = i_V_reg_458.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
         esl_seteq<1,1,1>(exitcond7_i_fu_365_p2.read(), ap_const_lv1_0) && 
         !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
  ap_sig_176.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
  ap_sig_189.read())))) {
        sof_1_i_fu_114 = ap_const_lv1_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        sof_1_i_fu_114 = ap_const_lv1_1;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
  ap_sig_176.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
  ap_sig_189.read())))) {
        exitcond7_i_reg_463 = exitcond7_i_fu_365_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        i_V_reg_458 = i_V_fu_355_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && !ap_sig_152.read())) {
        img_cols_V_read_reg_429 = img_cols_V_dout.read();
        img_rows_V_read_reg_424 = img_rows_V_dout.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && esl_seteq<1,1,1>(exitcond7_i_fu_365_p2.read(), ap_const_lv1_0) && !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
  ap_sig_176.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
  ap_sig_189.read())))) {
        tmp_108_reg_481 = p_Val2_s_phi_fu_285_p4.read().range(15, 8);
        tmp_54_reg_486 = p_Val2_s_phi_fu_285_p4.read().range(23, 16);
        tmp_55_reg_491 = p_Val2_s_phi_fu_285_p4.read().range(31, 24);
        tmp_reg_476 = tmp_fu_385_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && !esl_seteq<1,1,1>(src_axi_TVALID.read(), ap_const_logic_0))) {
        tmp_data_V_reg_434 = src_axi_TDATA.read();
        tmp_last_V_reg_442 = src_axi_TLAST.read();
    }
}

void filt_AXIvideo2Mat::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_done_reg.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond6_i_fu_350_p2.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void filt_AXIvideo2Mat::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void filt_AXIvideo2Mat::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond6_i_fu_350_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void filt_AXIvideo2Mat::thread_ap_reg_phiprechg_axi_last_V_2_i_reg_268pp1_it0() {
    ap_reg_phiprechg_axi_last_V_2_i_reg_268pp1_it0 =  (sc_lv<1>) ("X");
}

void filt_AXIvideo2Mat::thread_ap_reg_phiprechg_p_Val2_s_reg_281pp1_it0() {
    ap_reg_phiprechg_p_Val2_s_reg_281pp1_it0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
}

void filt_AXIvideo2Mat::thread_ap_sig_106() {
    ap_sig_106 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(5, 5));
}

void filt_AXIvideo2Mat::thread_ap_sig_152() {
    ap_sig_152 = (esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(img_rows_V_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(img_cols_V_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(img_rows_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(img_cols_V_out_full_n.read(), ap_const_logic_0));
}

void filt_AXIvideo2Mat::thread_ap_sig_171() {
    ap_sig_171 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void filt_AXIvideo2Mat::thread_ap_sig_176() {
    ap_sig_176 = (esl_seteq<1,1,1>(exitcond7_i_fu_365_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_lv1_0, brmerge_i_fu_379_p2.read()) && esl_seteq<1,1,1>(src_axi_TVALID.read(), ap_const_logic_0));
}

void filt_AXIvideo2Mat::thread_ap_sig_189() {
    ap_sig_189 = ((esl_seteq<1,1,1>(ap_const_lv1_0, exitcond7_i_reg_463.read()) && 
  esl_seteq<1,1,1>(img_data_stream_0_V_full_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond7_i_reg_463.read()) && 
  esl_seteq<1,1,1>(img_data_stream_1_V_full_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond7_i_reg_463.read()) && 
  esl_seteq<1,1,1>(img_data_stream_2_V_full_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond7_i_reg_463.read()) && 
  esl_seteq<1,1,1>(img_data_stream_3_V_full_n.read(), ap_const_logic_0)));
}

void filt_AXIvideo2Mat::thread_ap_sig_197() {
    ap_sig_197 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
  ap_sig_176.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
  ap_sig_189.read())));
}

void filt_AXIvideo2Mat::thread_ap_sig_209() {
    ap_sig_209 = (esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_i_reg_317.read()) && esl_seteq<1,1,1>(src_axi_TVALID.read(), ap_const_logic_0));
}

void filt_AXIvideo2Mat::thread_ap_sig_227() {
    ap_sig_227 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(6, 6));
}

void filt_AXIvideo2Mat::thread_ap_sig_234() {
    ap_sig_234 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void filt_AXIvideo2Mat::thread_ap_sig_25() {
    ap_sig_25 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void filt_AXIvideo2Mat::thread_ap_sig_255() {
    ap_sig_255 = (esl_seteq<1,1,1>(exitcond7_i_fu_365_p2.read(), ap_const_lv1_0) && !esl_seteq<1,1,1>(ap_const_lv1_0, brmerge_i_fu_379_p2.read()));
}

void filt_AXIvideo2Mat::thread_ap_sig_275() {
    ap_sig_275 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && esl_seteq<1,1,1>(exitcond7_i_fu_365_p2.read(), ap_const_lv1_0));
}

void filt_AXIvideo2Mat::thread_ap_sig_79() {
    ap_sig_79 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void filt_AXIvideo2Mat::thread_ap_sig_86() {
    ap_sig_86 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(4, 4));
}

void filt_AXIvideo2Mat::thread_ap_sig_99() {
    ap_sig_99 = (esl_seteq<1,1,1>(exitcond7_i_fu_365_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_lv1_0, brmerge_i_fu_379_p2.read()));
}

void filt_AXIvideo2Mat::thread_ap_sig_cseq_ST_pp1_stg0_fsm_4() {
    if (ap_sig_86.read()) {
        ap_sig_cseq_ST_pp1_stg0_fsm_4 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_pp1_stg0_fsm_4 = ap_const_logic_0;
    }
}

void filt_AXIvideo2Mat::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_25.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void filt_AXIvideo2Mat::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_79.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void filt_AXIvideo2Mat::thread_ap_sig_cseq_ST_st3_fsm_2() {
    if (ap_sig_234.read()) {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    }
}

void filt_AXIvideo2Mat::thread_ap_sig_cseq_ST_st4_fsm_3() {
    if (ap_sig_171.read()) {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    }
}

void filt_AXIvideo2Mat::thread_ap_sig_cseq_ST_st7_fsm_5() {
    if (ap_sig_106.read()) {
        ap_sig_cseq_ST_st7_fsm_5 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st7_fsm_5 = ap_const_logic_0;
    }
}

void filt_AXIvideo2Mat::thread_ap_sig_cseq_ST_st8_fsm_6() {
    if (ap_sig_227.read()) {
        ap_sig_cseq_ST_st8_fsm_6 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st8_fsm_6 = ap_const_logic_0;
    }
}

void filt_AXIvideo2Mat::thread_axi_data_V_1_i_phi_fu_237_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond7_i_reg_463.read()))) {
        axi_data_V_1_i_phi_fu_237_p4 = p_Val2_s_reg_281.read();
    } else {
        axi_data_V_1_i_phi_fu_237_p4 = axi_data_V_1_i_reg_234.read();
    }
}

void filt_AXIvideo2Mat::thread_brmerge_i_fu_379_p2() {
    brmerge_i_fu_379_p2 = (sof_1_i_fu_114.read() | eol_i_phi_fu_260_p4.read());
}

void filt_AXIvideo2Mat::thread_eol_i_phi_fu_260_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond7_i_reg_463.read()))) {
        eol_i_phi_fu_260_p4 = axi_last_V_2_i_reg_268.read();
    } else {
        eol_i_phi_fu_260_p4 = eol_i_reg_256.read();
    }
}

void filt_AXIvideo2Mat::thread_eol_phi_fu_226_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond7_i_reg_463.read()))) {
        eol_phi_fu_226_p4 = axi_last_V_2_i_reg_268.read();
    } else {
        eol_phi_fu_226_p4 = eol_reg_223.read();
    }
}

void filt_AXIvideo2Mat::thread_exitcond6_i_fu_350_p2() {
    exitcond6_i_fu_350_p2 = (!p_cast_cast_i_fu_346_p1.read().is_01() || !img_rows_V_read_reg_424.read().is_01())? sc_lv<1>(): sc_lv<1>(p_cast_cast_i_fu_346_p1.read() == img_rows_V_read_reg_424.read());
}

void filt_AXIvideo2Mat::thread_exitcond7_i_fu_365_p2() {
    exitcond7_i_fu_365_p2 = (!p_4_cast_cast_i_fu_361_p1.read().is_01() || !img_cols_V_read_reg_429.read().is_01())? sc_lv<1>(): sc_lv<1>(p_4_cast_cast_i_fu_361_p1.read() == img_cols_V_read_reg_429.read());
}

void filt_AXIvideo2Mat::thread_i_V_fu_355_p2() {
    i_V_fu_355_p2 = (!p_i_reg_212.read().is_01() || !ap_const_lv8_1.is_01())? sc_lv<8>(): (sc_biguint<8>(p_i_reg_212.read()) + sc_biguint<8>(ap_const_lv8_1));
}

void filt_AXIvideo2Mat::thread_img_cols_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        img_cols_V_blk_n = img_cols_V_empty_n.read();
    } else {
        img_cols_V_blk_n = ap_const_logic_1;
    }
}

void filt_AXIvideo2Mat::thread_img_cols_V_out_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        img_cols_V_out_blk_n = img_cols_V_out_full_n.read();
    } else {
        img_cols_V_out_blk_n = ap_const_logic_1;
    }
}

void filt_AXIvideo2Mat::thread_img_cols_V_out_din() {
    img_cols_V_out_din = img_cols_V_dout.read();
}

void filt_AXIvideo2Mat::thread_img_cols_V_out_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !ap_sig_152.read())) {
        img_cols_V_out_write = ap_const_logic_1;
    } else {
        img_cols_V_out_write = ap_const_logic_0;
    }
}

void filt_AXIvideo2Mat::thread_img_cols_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !ap_sig_152.read())) {
        img_cols_V_read = ap_const_logic_1;
    } else {
        img_cols_V_read = ap_const_logic_0;
    }
}

void filt_AXIvideo2Mat::thread_img_data_stream_0_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond7_i_reg_463.read()))) {
        img_data_stream_0_V_blk_n = img_data_stream_0_V_full_n.read();
    } else {
        img_data_stream_0_V_blk_n = ap_const_logic_1;
    }
}

void filt_AXIvideo2Mat::thread_img_data_stream_0_V_din() {
    img_data_stream_0_V_din = tmp_reg_476.read();
}

void filt_AXIvideo2Mat::thread_img_data_stream_0_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond7_i_reg_463.read()) && 
         !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
  ap_sig_176.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
  ap_sig_189.read())))) {
        img_data_stream_0_V_write = ap_const_logic_1;
    } else {
        img_data_stream_0_V_write = ap_const_logic_0;
    }
}

void filt_AXIvideo2Mat::thread_img_data_stream_1_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond7_i_reg_463.read()))) {
        img_data_stream_1_V_blk_n = img_data_stream_1_V_full_n.read();
    } else {
        img_data_stream_1_V_blk_n = ap_const_logic_1;
    }
}

void filt_AXIvideo2Mat::thread_img_data_stream_1_V_din() {
    img_data_stream_1_V_din = tmp_108_reg_481.read();
}

void filt_AXIvideo2Mat::thread_img_data_stream_1_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond7_i_reg_463.read()) && 
         !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
  ap_sig_176.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
  ap_sig_189.read())))) {
        img_data_stream_1_V_write = ap_const_logic_1;
    } else {
        img_data_stream_1_V_write = ap_const_logic_0;
    }
}

void filt_AXIvideo2Mat::thread_img_data_stream_2_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond7_i_reg_463.read()))) {
        img_data_stream_2_V_blk_n = img_data_stream_2_V_full_n.read();
    } else {
        img_data_stream_2_V_blk_n = ap_const_logic_1;
    }
}

void filt_AXIvideo2Mat::thread_img_data_stream_2_V_din() {
    img_data_stream_2_V_din = tmp_54_reg_486.read();
}

void filt_AXIvideo2Mat::thread_img_data_stream_2_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond7_i_reg_463.read()) && 
         !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
  ap_sig_176.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
  ap_sig_189.read())))) {
        img_data_stream_2_V_write = ap_const_logic_1;
    } else {
        img_data_stream_2_V_write = ap_const_logic_0;
    }
}

void filt_AXIvideo2Mat::thread_img_data_stream_3_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond7_i_reg_463.read()))) {
        img_data_stream_3_V_blk_n = img_data_stream_3_V_full_n.read();
    } else {
        img_data_stream_3_V_blk_n = ap_const_logic_1;
    }
}

void filt_AXIvideo2Mat::thread_img_data_stream_3_V_din() {
    img_data_stream_3_V_din = tmp_55_reg_491.read();
}

void filt_AXIvideo2Mat::thread_img_data_stream_3_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond7_i_reg_463.read()) && 
         !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
  ap_sig_176.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
  ap_sig_189.read())))) {
        img_data_stream_3_V_write = ap_const_logic_1;
    } else {
        img_data_stream_3_V_write = ap_const_logic_0;
    }
}

void filt_AXIvideo2Mat::thread_img_rows_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        img_rows_V_blk_n = img_rows_V_empty_n.read();
    } else {
        img_rows_V_blk_n = ap_const_logic_1;
    }
}

void filt_AXIvideo2Mat::thread_img_rows_V_out_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        img_rows_V_out_blk_n = img_rows_V_out_full_n.read();
    } else {
        img_rows_V_out_blk_n = ap_const_logic_1;
    }
}

void filt_AXIvideo2Mat::thread_img_rows_V_out_din() {
    img_rows_V_out_din = img_rows_V_dout.read();
}

void filt_AXIvideo2Mat::thread_img_rows_V_out_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !ap_sig_152.read())) {
        img_rows_V_out_write = ap_const_logic_1;
    } else {
        img_rows_V_out_write = ap_const_logic_0;
    }
}

void filt_AXIvideo2Mat::thread_img_rows_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !ap_sig_152.read())) {
        img_rows_V_read = ap_const_logic_1;
    } else {
        img_rows_V_read = ap_const_logic_0;
    }
}

void filt_AXIvideo2Mat::thread_j_V_fu_370_p2() {
    j_V_fu_370_p2 = (!p_4_i_reg_245.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(p_4_i_reg_245.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void filt_AXIvideo2Mat::thread_p_4_cast_cast_i_fu_361_p1() {
    p_4_cast_cast_i_fu_361_p1 = esl_zext<10,9>(p_4_i_reg_245.read());
}

void filt_AXIvideo2Mat::thread_p_Val2_s_phi_fu_285_p4() {
    if (ap_sig_275.read()) {
        if (!esl_seteq<1,1,1>(ap_const_lv1_0, brmerge_i_fu_379_p2.read())) {
            p_Val2_s_phi_fu_285_p4 = axi_data_V_1_i_phi_fu_237_p4.read();
        } else if (esl_seteq<1,1,1>(ap_const_lv1_0, brmerge_i_fu_379_p2.read())) {
            p_Val2_s_phi_fu_285_p4 = src_axi_TDATA.read();
        } else {
            p_Val2_s_phi_fu_285_p4 = ap_reg_phiprechg_p_Val2_s_reg_281pp1_it0.read();
        }
    } else {
        p_Val2_s_phi_fu_285_p4 = ap_reg_phiprechg_p_Val2_s_reg_281pp1_it0.read();
    }
}

void filt_AXIvideo2Mat::thread_p_cast_cast_i_fu_346_p1() {
    p_cast_cast_i_fu_346_p1 = esl_zext<9,8>(p_i_reg_212.read());
}

void filt_AXIvideo2Mat::thread_src_axi_TDATA_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
          esl_seteq<1,1,1>(exitcond7_i_fu_365_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, brmerge_i_fu_379_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_5.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_i_reg_317.read())))) {
        src_axi_TDATA_blk_n = src_axi_TVALID.read();
    } else {
        src_axi_TDATA_blk_n = ap_const_logic_1;
    }
}

void filt_AXIvideo2Mat::thread_src_axi_TREADY() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          !esl_seteq<1,1,1>(src_axi_TVALID.read(), ap_const_logic_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_5.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_i_reg_317.read()) && 
          !ap_sig_209.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
          esl_seteq<1,1,1>(exitcond7_i_fu_365_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, brmerge_i_fu_379_p2.read()) && 
          !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
  ap_sig_176.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
  ap_sig_189.read()))))) {
        src_axi_TREADY = ap_const_logic_1;
    } else {
        src_axi_TREADY = ap_const_logic_0;
    }
}

void filt_AXIvideo2Mat::thread_tmp_fu_385_p1() {
    tmp_fu_385_p1 = p_Val2_s_phi_fu_285_p4.read().range(8-1, 0);
}

void filt_AXIvideo2Mat::thread_tmp_user_V_fu_337_p1() {
    tmp_user_V_fu_337_p1 = src_axi_TUSER.read();
}

void filt_AXIvideo2Mat::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!ap_sig_152.read()) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if ((!esl_seteq<1,1,1>(src_axi_TVALID.read(), ap_const_logic_0) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_user_V_fu_337_p1.read()))) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else if ((!esl_seteq<1,1,1>(src_axi_TVALID.read(), ap_const_logic_0) && !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_user_V_fu_337_p1.read()))) {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            } else {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_st4_fsm_3;
            break;
        case 8 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond6_i_fu_350_p2.read())) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_pp1_stg0_fsm_4;
            }
            break;
        case 16 : 
            if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
  ap_sig_176.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
  ap_sig_189.read())) && !esl_seteq<1,1,1>(exitcond7_i_fu_365_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_pp1_stg0_fsm_4;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
  ap_sig_176.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
  ap_sig_189.read())) && !esl_seteq<1,1,1>(exitcond7_i_fu_365_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_st7_fsm_5;
            } else {
                ap_NS_fsm = ap_ST_pp1_stg0_fsm_4;
            }
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_i_reg_317.read()) && !ap_sig_209.read())) {
                ap_NS_fsm = ap_ST_st7_fsm_5;
            } else if ((!ap_sig_209.read() && !esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_i_reg_317.read()))) {
                ap_NS_fsm = ap_ST_st8_fsm_6;
            } else {
                ap_NS_fsm = ap_ST_st7_fsm_5;
            }
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_st4_fsm_3;
            break;
        default : 
            ap_NS_fsm = "XXXXXXX";
            break;
    }
}

}

